apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: b4mad-minecraft
resources:
  - creative
  - survival
  - papermc
  - github.com/Alex-exe-dev/income-and-expenditure-manager/manifests?ref=main
