apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
  annotations:
    {}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31904
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: minecraft-server
  sessionAffinity: None
  type: NodePort
