apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: b4mad-minecraft
generators:
  - secret-generator.yaml
resources:
  - deployments.yaml
  - persistent-volume-claims.yaml
  - services.yaml
