kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-server-paper-datadir
  labels:
    app: minecraft-server-paper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
