apiVersion: v1
kind: Secret
metadata:
    name: minecraft-server-paper
    labels:
        app: minecraft-server-paper
type: Opaque
data:
    rcon-password: ENC[AES256_GCM,data:Tv1puLDJAZgMngb+,iv:5NAhAYO0OdHWWawiUjLBCnig3B1mXDTSx1M9lPjVej0=,tag:EDVfQjtscD8pfPori2N96Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-25T20:21:48Z'
    mac: ENC[AES256_GCM,data:7ieBC1aTzw3D3xq68CoUH5c7w7J8r2WZqvNg81bKZ6Mr2lh7xo4kdreHEQGEOM78MaP7cht4t0qc9OWNtk2eQuwGbDCKcvIjD/otfcg/rrR8Q0vQQJE/+6Ur4pkwHaB3yNP1fQhGR1/HLTEQleegoDXksyXpdUvkjEw1ppV6LT0=,iv:IinbMnj7OpS8EwEi1Q7bf03ujw32fIlf6T26CgFxH4w=,tag:+ypfnFgwFmzen+dvK3K1ug==,type:str]
    pgp:
    -   created_at: '2021-03-24T08:00:09Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAANbOxZCWO74KkMCugMsGhQEJ0SARF1FTrS/Ci4jDWT6zO
            myxiVdpjbKYBKJiiNceF+NA9f/z1kqzRR0ZDKfeoPIvH9nTsoUsZWAZuM6Wgezdr
            DZ+XWnS60n13M1SetkJhb/OMZK0+8oZIKhLuYxovXrS6XmysXjNKVJ47jAK6Df9o
            Q/HaffXyQA7M49gPb0pMTVNs3DUgfRpPHJTkCgRmflieZCcD8+nzJxtlSAmSD9vW
            qGBJ2UM1kv7XexzHWEhDwr2VU7Ci4VI/JwAOjVUpzgdQO2nIWGYsD7XH2pBSoK9m
            CUA24gKKgvYXP5tVeHAFCWjU9KqxcrSN4sKgr5qt+3/mG9oblSsLU8OO408uMnMf
            dqm7OBpjRnETHvu7aAwmfkx7mFvQnJEmO02OSyEWpeDM78Oq8vtlc3OxnGX93DQr
            RyD/MKo2j9tGlmkM5daaDxBpPETz2BkMOUoKjdSmybufjQeUDjm5kVwQiaqjLBBz
            q46+te11zqCDJ5MUwvE6XUQC1X23mxdfaYHXOH/xNAM3BVaKDzVKEWg5PGgREwpv
            OsvGpJG7IlQtmyTkYKlzNW9nsE4+kIuuDDns8IK/A6JUs95IY/aRO3JABcMZ80tp
            zP/hAxpxqs3WCBAri70aFwIhIdBi9LXVgLJP/h5m3kn00k+pqqXB/MhAsS5/9YjS
            4AHkCUT9/fH0Slck82jVKe1CU+FP6uDU4FHhR4LgGeJA50sC4NjlFkiPMtRfNDgy
            VuFsXasBYe3nwNPrNzLOisELfogh4r7gwOR/3VU1v9eZT+tL6naiWzrM4gowZIXh
            KHUA
            =eI1X
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2021-03-24T08:00:09Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9AgVmznaOk7ARAAUho/tMNEjgFs63yZWQoqA2WkAkuXSfmVIJvnADuTpcIY
            lI/CcF2R+TmTvSuQMSwMNDfRfvJeSeYtcocwJfpGHYphVXIrfzJKzbP27jelR0Bs
            kzIDGWpPDyj6ut+KIS3bukGjmcxm/JIHJ3fcpKFUNVUjvkEVRIzLccB8KVxTpuYr
            9WoWM+2pCh0ePAJR8VSaJdRCrmOTUW+2rwToBUYb4zsAnxGff3pOXX6+yG7jgd1R
            mGoMbWdhobrsiJcl0aKGZ09ahP864CK+oP31otqFOdkEUVpIZAJI3+paJZ3kF8CU
            3aArJ5NnFTTFw7Ty1oVhJU/dM0vtqj6EmkB45R5Z4UQzsvACa+EpwsJTeO1vIUz+
            RbiSqnMdjv1i/ihebDSDemo5tltamVM1CYzgE7ioMrZ4QEccCRfuCTzS2d95iFhT
            zhMJMROrQreB7XcL3V1xuApvgjNznuiGUozJS0G4SlBK1IvEtz7h/E7lyYwaxfyy
            jzD1BXiATWy6ZLNdrqb1LbPSevTLl28nlqxqEJu3x7eXgQodC+MovKgK+zSvAoFZ
            jjIZjqubjjeEgK8qgt4uUaPTrC3sjDLEjWfRX5BsEpwzfmJbdQ/IwJlnse+pk7Mx
            l8nRDTAJMdZUUW5jRGGa9DwJQHcdyoMIbsVWJIcit72unsj1TWblu6UQJFEra1/S
            4AHkSJjijFyOs9j8Z+EW+3B2zuH+HuBe4IfhppngJuLVOMEW4Hjl5qdxQPUzi+Aj
            H/AryWjY3qzork578/TzkPl8sm5L9D3gleRd2mf6quUOk8qx73nJZW/Q4guJGZLh
            9QoA
            =Z9KD
            -----END PGP MESSAGE-----
        fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
    -   created_at: '2021-03-24T08:00:09Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAAptsSnf1WGkaSsIVp3KVeZm+5grmDOlDFm0tMTY1ZZOkS
            1RtHKKFChsqQtstsZ4QME6Co4ELUb/AsJ4U3zGi5NEZ7jMyY5E/g/s/RZTe4/o5f
            cgJ5TNbZFnf3ILD7m7HeSF/yOohBd2l6jPswmeHA62NVRDsr6bcvZ8+ItA53ZteL
            ilkFGQC/hpcRc+I/49sDKXqRnXrdlpOEIMob2ZJPkr5j1gazuZLi3Zb3xpM9+APE
            yicDfWgVYAqMcv91XcV9G0HaEEa61oN1s3H8TKzGTxip8ihF6oUO4SGfQ8Q1oeoG
            59Q+0+7pOiFJpaoHb1DsOG+TrpX4Osy64kT0aWvEWyTvXQSo2FSRk43MT2Lq3bdh
            cWJv1OZb844Ahns0FAMjzpOjp/HwHyoXXS8QFKOl6hO68SMGl4oA6s6P1nW6iTCB
            /1wrA6ZXZe72kHWHwMroVESZxk5gV6NeWrJKCHImbjBhm0p7A/Ro3TT1AuvymL0G
            0/yAvAleJ0SedEa7/i6JLIVHnaFry9+NOA+s3DSJOmXTuZIdLgp9cK5qZB912xEf
            HXJVRMH6GC0DN+EWEwBNY7MM0V+VWdWOx08lVNgB+dKL/G5F/Wca6xQ0a56dhvEL
            tiLt51s7HIoVmZlmu0dE+tNsHuppti1JLDO+Sw7NKgj7eFahIEu2zoiedKvyTVTS
            4AHkyBbPUVc0da7RzAFKjYBUv+GlM+AP4CzhjoXgnOIRaj2q4BrlfGblxJejkoQr
            D+uFU07Zrl34HpPeyqc6csnMVwDcp9LgMuQHsTJXWqUkDnvKz0pcIEkf4rpZnCvh
            6gsA
            =xgfs
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
